name: background_locator
description: A Flutter plugin for updating location in background.
version: 0.0.4-beta
homepage: https://github.com/rekab-app/background_locator

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: rekab.app.background_locator
    pluginClass: BackgroundLocatorPlugin